services:
    db:
        image: postgres:17
        environment:
            - POSTGRES_DB=food
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
        ports:
            - "5432:5432"
        networks:
            - menu-crud
    app:
      build: .
      depends_on:
        - db
      ports:
        - "8080:8080"
      networks:
        - menu-crud
      healthcheck:
        test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1" ]
        interval: 10s
        timeout: 5s
        retries: 5
    nginx:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - app

networks:
  menu-crud:
    driver: bridge