services:
    db:
        image: postgres:17
        environment:
            - POSTGRES_DB=food
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
        ports:
            - "5432:5432"
#        networks:
#            - menu-crud
#    app:
#      build: .
#      depends_on:
#        - db
#      ports:
#        - "8080:8080"
#      networks:
#        - menu-crud
#
#networks:
#  menu-crud:
#    driver: bridge