services:
    db:
        image: postgres:17
        environment:
            - POSTGRES_DB=food
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
        ports:
            - "5432:5432"